name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dateutil backoff monotonic
          pip install --user .
          sudo pip install pylint==2.8.0 flake8 mock==3.0.5 python-dateutil
      - name: Run tests
        run: make e2e_test

#  snyk:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      #- attach_workspace: { at: . }
#      - run: pip3 install pipreqs
#      - run: pip3 install --user appdirs
#      - run: pipreqs .
#      - run: pip3 install --user -r requirements.txt
#      - run: curl -sL https://raw.githubusercontent.com/segmentio/snyk_helpers/master/initialization/snyk.sh | sh#

#  test:
#    #needs: ['coding-standard', 'lint']
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
#        coverage: [false]
#        experimental: [false]
#        include:
#          # Run code coverage.
#          - python: '3.7'
#            coverage: true
#            experimental: false
#          - python: '3.8'
#            coverage: true
#            experimental: false
#          - python: '3.9'
#            coverage: true
#            experimental: false
#          - python: '3.10'
#            coverage: true
#            experimental: false  
#          - python: '3.11'
#            coverage: true
#            experimental: false  